version: "3.7"
services:
   mongo:
    container_name: mongo-service
    image: mongo
    logging:
      driver: none
    expose:
      - 27017
    ports: 
      - 27017:27017
    volumes:
      - mongodb:/data/db
   backend:
    container_name: back-end-express
    command: sh -c "npm start" #"npm run test && npm start"
    restart: always 
    build: 
        context: ./backend
        dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes: #
      - ./backend:/usr/src/app
    environment:
      - MONGO_URL=mongodb://mongo:27017
   front:
    container_name: front-end-vue
    command: sh -c "npm run test && npm run serve"
    restart: always 
    build: 
        context: ./frontend
        dockerfile: dockerfile
    ports:
      - 8081:8080
    volumes: #
      - ./frontend:/usr/src/app
   mongo_express:
    container_name: mongo_express_url_shortener
    image: mongo-express
    logging:
      driver: none
    links:
      - mongo
    ports:
      - "8083:8081"
volumes:
  mongodb:
