version: "3.7"
services:
  mongo:
    container_name: mongo-service
    image: mongo
    logging:
      driver: none
    expose:
      - 27017
    volumes:
      - mongodb:/data/db
  backend:
    container_name: back-end-express
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongo:27017
  front:
    container_name: front-end-vue
    restart: always
    build:
      context: ./frontend
      dockerfile: dockerfile.prod
    ports:
      - 8081:8080
volumes:
  mongodb:
