version: "3.7"
services:
   front:
    container_name: front-end-vue
    command: sh -c "npm run test && npm run serve"
    restart: always 
    build: 
        context: ./frontend
        dockerfile: dockerfile
    ports:
      - 8081:8080
    volumes: #
      - ./frontend:/usr/src/app
